name: LapisInventories
version: ${project.version}
main: net.lapismc.lapisinventories.LapisInventories
api-version: 1.13
authors: [Dart2112]
description: A basic GameMode based inventory management system
commands:
  lapisinventories:
    description: Use "/lapisinventories help" for help
permissions:
  LapisInventories.canDrop:
    decsription: Players with this permission will be able to drop/pickup items in creative
  LapisInventories.containerAccess:
    description: Players with this permission will be able to access containers in creative
  LapisInventories.checkBlocks:
    description: Players with this permission will be able to check if a block was placed in creative with a blaze rod
  LapisInventories.bypassLogging:
    description: Players with this permission will not have creative blocks logged
  LapisInventories.canUpdate:
    decsription: Players with this permission will be able to download updates with /lapisinventories update, they will also be notified of updates